{{ if .Values.gateway.enabled }}
---
apiVersion: {{ template "taiga.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "taiga.fullname" . }}-gateway
  labels: {{- include "taiga.gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "taiga.gateway.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.gateway.replicas }}
  template:
    metadata:
      labels: {{- include "taiga.gateway.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "taiga.name" . }}-gateway
      {{- if .Values.gateway.podAnnotations }}
      annotations:
        {{- include "taiga.tplValue" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "taiga.gateway.imagePullSecrets" . | indent 6 }}
      {{- if .Values.gateway.affinity }}
      affinity: {{- include "redmine.tplValue" (dict "value" .Values.gateway.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.nodeSelector }}
      nodeSelector: {{- include "taiga.tplValue" (dict "value" .Values.gateway.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.tolerations }}
      tolerations: {{- include "redmine.tplValue" (dict "value" .Values.gateway.tolerations "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "taiga.serviceAccountName" . }}
      {{- with .Values.gateway.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      # https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/
      - name: {{ template "taiga.fullname" . }}-gateway
        image: {{ template "taiga.gateway.image" . }}
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy | quote }}
        {{- if .Values.gateway.resources }}
        resources: {{ toYaml .Values.gateway.resources | nindent 12 }}
        {{- end }}
        ports:
          - name: taiga-gateway
            containerPort: 80
        {{- if .Values.gateway.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /admin/login/
            port: 80
          initialDelaySeconds: {{ .Values.gateway.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.gateway.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.gateway.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.gateway.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.gateway.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.gateway.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /admin/login/
            port: 80
          initialDelaySeconds: {{ .Values.gateway.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.gateway.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.gateway.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.gateway.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.gateway.readinessProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
          - name: taiga-static
            mountPath: /taiga/static
          - name: taiga-media
            mountPath: /taiga/media
          - name: taiga-conf
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: taiga-static
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "taiga.fullname" .) }}-static
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: taiga-media
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "taiga.fullname" .) }}-media
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: taiga-conf
          configMap:
            name: {{ template "taiga.fullname" . }}-gateway
{{ end }}
